// Mock problems data
export const mockProblems = [
  {
    id: 1,
    title: "Two Sum",
    difficulty: "Easy",
    description:
      "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target. You may assume that each input would have exactly one solution, and you may not use the same element twice.",
    acceptanceRate: 48,
    tags: ["Array", "Hash Table"],
    solved: true,
    featured: true,
  },
  {
    id: 2,
    title: "Add Two Numbers",
    difficulty: "Medium",
    description:
      "You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.",
    acceptanceRate: 36,
    tags: ["Linked List", "Math", "Recursion"],
    solved: false,
    featured: true,
  },
  {
    id: 3,
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    description: "Given a string s, find the length of the longest substring without repeating characters.",
    acceptanceRate: 32,
    tags: ["Hash Table", "String", "Sliding Window"],
    solved: false,
    featured: true,
  },
  {
    id: 4,
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    description:
      "Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.",
    acceptanceRate: 31,
    tags: ["Array", "Binary Search", "Divide and Conquer"],
    solved: false,
    featured: false,
  },
  {
    id: 5,
    title: "Longest Palindromic Substring",
    difficulty: "Medium",
    description: "Given a string s, return the longest palindromic substring in s.",
    acceptanceRate: 30,
    tags: ["String", "Dynamic Programming"],
    solved: true,
    featured: false,
  },
  {
    id: 6,
    title: "ZigZag Conversion",
    difficulty: "Medium",
    description:
      "The string 'PAYPALISHIRING' is written in a zigzag pattern on a given number of rows. Write the code that will take a string and make this conversion.",
    acceptanceRate: 39,
    tags: ["String"],
    solved: false,
    featured: false,
  },
  {
    id: 7,
    title: "Reverse Integer",
    difficulty: "Medium",
    description:
      "Given a signed 32-bit integer x, return x with its digits reversed. If reversing x causes the value to go outside the signed 32-bit integer range, then return 0.",
    acceptanceRate: 26,
    tags: ["Math"],
    solved: true,
    featured: false,
  },
  {
    id: 8,
    title: "String to Integer (atoi)",
    difficulty: "Medium",
    description: "Implement the myAtoi(string s) function, which converts a string to a 32-bit signed integer.",
    acceptanceRate: 15,
    tags: ["String", "Math"],
    solved: false,
    featured: false,
  },
  {
    id: 9,
    title: "Palindrome Number",
    difficulty: "Easy",
    description:
      "Given an integer x, return true if x is palindrome integer. An integer is a palindrome when it reads the same backward as forward.",
    acceptanceRate: 51,
    tags: ["Math"],
    solved: true,
    featured: true,
  },
  {
    id: 10,
    title: "Regular Expression Matching",
    difficulty: "Hard",
    description:
      "Given an input string s and a pattern p, implement regular expression matching with support for '.' and '*'.",
    acceptanceRate: 27,
    tags: ["String", "Dynamic Programming", "Recursion"],
    solved: false,
    featured: false,
  },
  {
    id: 11,
    title: "Container With Most Water",
    difficulty: "Medium",
    description:
      "Given n non-negative integers a1, a2, ..., an, where each represents a point at coordinate (i, ai). n vertical lines are drawn such that the two endpoints of the line i is at (i, ai) and (i, 0). Find two lines, which, together with the x-axis forms a container, such that the container contains the most water.",
    acceptanceRate: 52,
    tags: ["Array", "Two Pointers", "Greedy"],
    solved: false,
    featured: false,
  },
  {
    id: 12,
    title: "Integer to Roman",
    difficulty: "Medium",
    description:
      "Roman numerals are represented by seven different symbols: I, V, X, L, C, D and M. Given an integer, convert it to a roman numeral.",
    acceptanceRate: 57,
    tags: ["Math", "String"],
    solved: false,
    featured: false,
  },
]

// Mock users data
export const mockUsers = [
  {
    id: 1,
    name: "Alex Johnson",
    avatar: "/placeholder.svg?height=40&width=40",
    score: 9850,
    problemsSolved: 342,
    level: "Master",
    bio: "Software Engineer at Google. Passionate about algorithms and competitive programming.",
    joinDate: "Jan 2020",
  },
  {
    id: 2,
    name: "Sarah Chen",
    avatar: "/placeholder.svg?height=40&width=40",
    score: 8720,
    problemsSolved: 315,
    level: "Expert",
    bio: "CS Student at MIT. 3x ICPC Finalist. Teaching assistant for algorithms course.",
    joinDate: "Mar 2021",
  },
  {
    id: 3,
    name: "Michael Rodriguez",
    avatar: "/placeholder.svg?height=40&width=40",
    score: 8150,
    problemsSolved: 298,
    level: "Expert",
    bio: "Full-stack developer with a passion for solving complex problems. Contributor to open-source projects.",
    joinDate: "Nov 2020",
  },
  {
    id: 4,
    name: "Emily Wong",
    avatar: "/placeholder.svg?height=40&width=40",
    score: 7890,
    problemsSolved: 276,
    level: "Advanced",
    bio: "Software Developer at Amazon. Loves competitive programming and mentoring beginners.",
    joinDate: "Feb 2021",
  },
  {
    id: 5,
    name: "David Kim",
    avatar: "/placeholder.svg?height=40&width=40",
    score: 7650,
    problemsSolved: 254,
    level: "Advanced",
    bio: "PhD student in Computer Science. Research focus on algorithms and computational complexity.",
    joinDate: "Apr 2020",
  },
  {
    id: 6,
    name: "Lisa Patel",
    avatar: "/placeholder.svg?height=40&width=40",
    score: 7320,
    problemsSolved: 241,
    level: "Advanced",
    bio: "Backend Engineer at Microsoft. Competitive programmer since high school.",
    joinDate: "Jul 2021",
  },
  {
    id: 7,
    name: "James Wilson",
    avatar: "/placeholder.svg?height=40&width=40",
    score: 6980,
    problemsSolved: 228,
    level: "Intermediate",
    bio: "CS Major at Stanford. Interested in algorithms, machine learning, and distributed systems.",
    joinDate: "Sep 2021",
  },
  {
    id: 8,
    name: "Olivia Martinez",
    avatar: "/placeholder.svg?height=40&width=40",
    score: 6750,
    problemsSolved: 215,
    level: "Intermediate",
    bio: "Software Engineer at Facebook. Passionate about teaching and mentoring new programmers.",
    joinDate: "Dec 2020",
  },
  {
    id: 9,
    name: "Daniel Lee",
    avatar: "/placeholder.svg?height=40&width=40",
    score: 6540,
    problemsSolved: 203,
    level: "Intermediate",
    bio: "Full-stack developer and open source contributor. Loves solving algorithmic challenges.",
    joinDate: "Feb 2022",
  },
  {
    id: 10,
    name: "Sophia Brown",
    avatar: "/placeholder.svg?height=40&width=40",
    score: 6320,
    problemsSolved: 197,
    level: "Intermediate",
    bio: "Computer Science student and competitive programmer. Interested in graph algorithms and dynamic programming.",
    joinDate: "Mar 2021",
  },
]

